#!/usr/bin/env node

import fs from 'fs'
import path from 'path'
import minimist from 'minimist'

// Shim for internal compatibility
import { DefaultLoader, Declarer } from '../facilities'

const args = minimist(process.argv.slice(2))

function usage() {
  console.log(
    `usage: ${process.argv[1]} --dir=<template dir> -o ./templates.ts

options:
  --dir        the path to the mustache template directory
  -h           print these instructions and exit
  -o           the output path to write the decalaration file
  --node       optionally configure declaration file for use with node.js
`,
  )
  process.exit(2)
}

if (args.h || !args.dir || !args.o) {
  usage()
}

const loader = new DefaultLoader({ dir: args.dir })
const declarer = new Declarer(loader)

declarer.declare().then((declarations) => {
  const header = [
    `/**
*  Generated by ts-mustache at ${new Date().toISOString()}
*
*  @see {@link https://github.com/rjz/ts-mustache/}
*/`,
  ]

  const footer = []

  if (args.node && args.o) {
    header.push("import path from 'path'")
    footer.push(
      `export const TEMPLATE_DIR = path.resolve(__dirname, '${path.relative(
        path.dirname(args.o),
        path.resolve(args.dir),
      )}')`,
    )
  }

  const output = [...header, declarations, ...footer]
    .filter(Boolean)
    .join('\n\n')

  if (args.o) {
    fs.writeFileSync(args.o, output)
  } else {
    console.log(output)
  }
  process.exit(0)
})
